#!/bin/bash
sudo wget http://apt.puppetlabs.com/puppetlabs-release-stable.deb 2>&1 1>/dev/null;
sudo dpkg -i puppetlabs-release-stable.deb 2>&1 1>/dev/null;
sudo apt-get update 2>&1 1>/dev/null;
sudo apt-get install -y language-pack-en 2>&1 1>/dev/null;
sudo locale-gen en_US 2>&1 1>/dev/null;
sudo apt-get install -y puppetmaster puppet 2>&1 1>/dev/null;
